<center><h1> bsolar vs bolasso </h1></center>

  * <font size="4.5"> In this file we set the DGP identical to the one in simulation 1. </font>
  * <font size="4.5"> $p/n$ changes stagewise from $150/100$ to $200/150$ and $250/200$. </font>

## #1: import all modules

* <font size="4.5"> "pickle" is used to save all computation results into ".p" files, which can be loaded later. </font>

* <font size="4.5"> For simplicity and elegancy, all relevant functions and classes are coded in "simul_plot_parallel.py". </font>

In [1]:
%reset -f

from simul_plot_parallel import simul_plot

import numpy             as np
import matplotlib.pyplot as plt
import pandas            as pd
import pickle
import os
import errno

---

## #2: define all functions

## #2(a): computation and visualization

In [2]:
def func_simul(sample_size, n_dim, n_info, num_rep, step_size, rnd_seed, repro):
    
    #set random seed
    np.random.seed(rnd_seed)

    print("compute the simulation with sample size "+str(sample_size)+" and number of variables "+str(n_dim))

    trial = simul_plot(sample_size, n_dim, n_info, num_rep, step_size, rnd_seed)

    pkl_file = "./numerical_result/bsolar_simul_n_" + str(sample_size) + "_p_" + str(n_dim) + "_thre_1_bsolar_10.p"

    if repro == True:

        bsolar3S_Q_opt_c_stack, bsolar3H_Q_opt_c_stack, bsolar10S_Q_opt_c_stack, bsolar10H_Q_opt_c_stack, bsolar5S_Q_opt_c_stack, bsolar5H_Q_opt_c_stack, bolassoS_Q_opt_c_stack, bolassoH_Q_opt_c_stack = trial.simul_func()

        #save all the computation result into Pickle files
        #create the subdirectory if not existing
        if not os.path.exists(os.path.dirname(pkl_file)):
            try:
                os.makedirs(os.path.dirname(pkl_file))
            # Guard against race condition
            except OSError as exc: 
                if exc.errno != errno.EEXIST:
                    raise
        with open(pkl_file, "wb") as f:
            pickle.dump( bsolar3S_Q_opt_c_stack  , f)
            pickle.dump( bsolar3H_Q_opt_c_stack  , f)
            pickle.dump( bsolar10S_Q_opt_c_stack , f)
            pickle.dump( bsolar10H_Q_opt_c_stack , f)
            pickle.dump( bsolar5S_Q_opt_c_stack , f)
            pickle.dump( bsolar5H_Q_opt_c_stack , f)
            pickle.dump( bolassoS_Q_opt_c_stack  , f)
            pickle.dump( bolassoH_Q_opt_c_stack  , f)

    else:
        with open(pkl_file, "rb") as f:
            bsolar3S_Q_opt_c_stack  = pickle.load( f )
            bsolar3H_Q_opt_c_stack  = pickle.load( f )
            bsolar10S_Q_opt_c_stack = pickle.load( f )
            bsolar10H_Q_opt_c_stack = pickle.load( f )
            bsolar5S_Q_opt_c_stack  = pickle.load( f )
            bsolar5H_Q_opt_c_stack  = pickle.load( f )
            bolassoS_Q_opt_c_stack  = pickle.load( f )
            bolassoH_Q_opt_c_stack  = pickle.load( f )

    #compute the number of selected variable of both bsolar and blasso
    ## set the container
    bsolar3S_len_array  = np.empty(num_rep)
    bsolar3H_len_array  = np.empty(num_rep)
    bsolar10S_len_array = np.empty(num_rep)
    bsolar10H_len_array = np.empty(num_rep)
    bsolar5S_len_array  = np.empty(num_rep)
    bsolar5H_len_array  = np.empty(num_rep)
    bolassoS_len_array  = np.empty(num_rep)
    bolassoH_len_array  = np.empty(num_rep)

    ##count the number 
    for i in range(num_rep):
        bsolar3S_len_array[i]  = len(bsolar3S_Q_opt_c_stack[i])
        bsolar3H_len_array[i]  = len(bsolar3H_Q_opt_c_stack[i])
        bsolar10S_len_array[i] = len(bsolar10S_Q_opt_c_stack[i])
        bsolar10H_len_array[i] = len(bsolar10H_Q_opt_c_stack[i])
        bsolar5S_len_array[i] = len(bsolar5S_Q_opt_c_stack[i])
        bsolar5H_len_array[i] = len(bsolar5H_Q_opt_c_stack[i])
        bolassoS_len_array[i] = len(bolassoS_Q_opt_c_stack[i])
        bolassoH_len_array[i] = len(bolassoH_Q_opt_c_stack[i])

    #compute the marginal probability of selecting each informative variable
    ## set the container
    bsolar3S_var_array  = np.empty([5])
    bsolar3H_var_array  = np.empty([5])
    bsolar10S_var_array = np.empty([5])
    bsolar10H_var_array = np.empty([5])
    bsolar5S_var_array = np.empty([5])
    bsolar5H_var_array = np.empty([5])
    bolassoS_var_array = np.empty([5])
    bolassoH_var_array = np.empty([5])

    ##concatenate results
    bsolar3S_vari_appe_stack  = np.concatenate(bsolar3S_Q_opt_c_stack ,0)
    bsolar3H_vari_appe_stack  = np.concatenate(bsolar3H_Q_opt_c_stack ,0)
    bsolar10S_vari_appe_stack = np.concatenate(bsolar10S_Q_opt_c_stack,0)
    bsolar10H_vari_appe_stack = np.concatenate(bsolar10H_Q_opt_c_stack,0)
    bsolar5S_vari_appe_stack = np.concatenate(bsolar5S_Q_opt_c_stack,0)
    bsolar5H_vari_appe_stack = np.concatenate(bsolar5H_Q_opt_c_stack,0)
    bolassoS_vari_appe_stack = np.concatenate(bolassoS_Q_opt_c_stack,0)
    bolassoH_vari_appe_stack = np.concatenate(bolassoH_Q_opt_c_stack,0)

    ##count the number 
    for i in range(5):
        bsolar3S_var_array[i]  = (bsolar3S_vari_appe_stack  == i).sum()/num_rep
        bsolar3H_var_array[i]  = (bsolar3H_vari_appe_stack  == i).sum()/num_rep
        bsolar10S_var_array[i] = (bsolar10S_vari_appe_stack == i).sum()/num_rep
        bsolar10H_var_array[i] = (bsolar10H_vari_appe_stack == i).sum()/num_rep
        bsolar5S_var_array[i] = (bsolar5S_vari_appe_stack == i).sum()/num_rep
        bsolar5H_var_array[i] = (bsolar5H_vari_appe_stack == i).sum()/num_rep
        bolassoS_var_array[i] = (bolassoS_vari_appe_stack == i).sum()/num_rep
        bolassoH_var_array[i] = (bolassoH_vari_appe_stack == i).sum()/num_rep

    #sparsity table
    mean_col   = [np.mean(bsolar3S_len_array), np.mean(bsolar3H_len_array), 
                  np.mean(bsolar10S_len_array), np.mean(bsolar10H_len_array),
                  np.mean(bsolar5S_len_array), np.mean(bsolar5H_len_array),
                  np.mean(bolassoS_len_array), np.mean(bolassoH_len_array)]
    median_col = [np.median(bsolar3S_len_array), np.median(bsolar3H_len_array), 
                  np.median(bsolar10S_len_array), np.median(bsolar10H_len_array),
                  np.median(bsolar5S_len_array), np.median(bsolar5H_len_array),
                  np.median(bolassoS_len_array), np.median(bolassoH_len_array)]

    df1 = pd.concat([pd.DataFrame({'algo':['bsolar-3S','bsolar-3H',
                                           'bsolar-10S', 'bsolar-10H',
                                           'bsolar-5S', 'bsolar-5H',
                                           'bolasso-S', 'bolasso-H']}), 
                     pd.DataFrame({'Number of selected variables (mean)': mean_col}),
                     pd.DataFrame({'Number of selected variables (median)': median_col})], 
                    axis=1, join='inner')

    #accuracy table
    prob_0 = [bsolar3S_var_array[0] , bsolar3H_var_array[0], 
              bsolar10S_var_array[0], bsolar10H_var_array[0], 
              bsolar5S_var_array[0], bsolar5H_var_array[0], 
              bolassoS_var_array[0] , bolassoH_var_array[0]]
    
    prob_1 = [bsolar3S_var_array[1] , bsolar3H_var_array[1], 
              bsolar10S_var_array[1], bsolar10H_var_array[1], 
              bsolar5S_var_array[1], bsolar5H_var_array[1], 
              bolassoS_var_array[1] , bolassoH_var_array[1]]
    
    prob_2 = [bsolar3S_var_array[2] , bsolar3H_var_array[2], 
              bsolar10S_var_array[2], bsolar10H_var_array[2], 
              bsolar5S_var_array[2], bsolar5H_var_array[2], 
              bolassoS_var_array[2] , bolassoH_var_array[2]]
    
    prob_3 = [bsolar3S_var_array[3] , bsolar3H_var_array[3], 
              bsolar10S_var_array[3], bsolar10H_var_array[3], 
              bsolar5S_var_array[3], bsolar5H_var_array[3], 
              bolassoS_var_array[3] , bolassoH_var_array[3]]
    
    prob_4 = [bsolar3S_var_array[4] , bsolar3H_var_array[4], 
              bsolar10S_var_array[4], bsolar10H_var_array[4], 
              bsolar5S_var_array[4], bsolar5H_var_array[4], 
              bolassoS_var_array[4] , bolassoH_var_array[4]]

    df2 = pd.concat([pd.DataFrame({'algo':['bsolar-3S','bsolar-3H',
                                           'bsolar-10S', 'bsolar-10H',
                                           'bsolar-5S', 'bsolar-5H',
                                           'bolasso-S', 'bolasso-H']}), 
                     pd.DataFrame({'Pr(select X0)': prob_0}),
                     pd.DataFrame({'Pr(select X1)': prob_1}),
                     pd.DataFrame({'Pr(select X2)': prob_2}),
                     pd.DataFrame({'Pr(select X3)': prob_3}),
                     pd.DataFrame({'Pr(select X4)': prob_4})],
                    axis=1, join='inner')

    return df1.round(2), df2.round(2)

---

## #3(a): define inputs values

| <font size="4.5"> variable name </font> | <font size="4.5">  meaning </font> |
|-|-|
| <font size="4.5">  sample_size  </font> | <font size="4.5">  the sample size $n$ in the paper; </font>| 
| <font size="4.5">  n_dim        </font> | <font size="4.5">  the number of variables (informative + redundant) in $X$, $p$ in the paper; </font>| 
| <font size="4.5">  n_info       </font> | <font size="4.5">  the number of informative variables in $X$; </font>| 
| <font size="4.5">  num_rep      </font> | <font size="4.5">  the total repetition number of this simulation; </font>|
| <font size="4.5">  step_size    </font> | <font size="4.5">  the step size for tuning $c$; </font>| 
| <font size="4.5">  rnd_seed     </font> | <font size="4.5">  the random seed value; </font>| 

## #3(b): define DGP

* <font size="4.5"> the population regression equation is $$Y = 2\cdot \mathbf{x}_0 + 3\cdot \mathbf{x}_1 + 4\cdot \mathbf{x}_2 + 5\cdot \mathbf{x}_3 + 6\cdot \mathbf{x}_4  + u,$$ 
* <font size="4.5"> To change the simulation settings, simply change the input values. If you change *n_info* you will adjust the DGP as follows: </font>
    * <font size="4.5"> If $i > \mbox{n_info} - 1$ and $i \in \left[ 0, 1, 2, \ldots, p-1 \right]$, $\beta_i = 0$ in population;</font>
    * <font size="4.5"> If $i \leqslant \mbox{n_info} - 1$ and $i \in \left[ 0, 1, 2, \ldots, p-1 \right]$, $\beta_i = i + 2$ in population</font>

In [3]:
n_info    = 5
step_size = -0.01
num_rep   = 200
rnd_seed  = 0

sample_size_0 = 100;n_dim_0 = 150
sample_size_1 = 150;n_dim_1 = 200
sample_size_2 = 200;n_dim_2 = 250

---

## #4: Results comparison

 * <font size="5"> if you only want to see our raw result, set *repro=False* </font>
 * <font size="5"> for replication, set *repro=True* </font>

In [4]:
repro = False

  * <font size="4.5"> Numpy, Sklearn and Python are actively updated. If you use different version, replication results may be slightly different from the paper (see Read_me_first.pdf for detail). </font>

  * <font size="4.5"> To rerun this part, first delete all .p files in the "raw_result" folder to avoid possible bug. </font>

---
## **Read this before you move on** : the runtime length issue of bolasso

### Beware that bolasso computation could take very long time. On a Thinkpad T480 laptop with i5-8500u CPU and 8G Ram, bolasso takes around 60 mins for one repetition at $p/n=1200/600$ (200 hours for 200 repetitions in total).

### Please use a proper desktop with a 8-core CPU if you want to replicate the bolasso result as quick as possible

---

## #4(a): $p/n=150/100$

In [5]:
df1, df2 = func_simul(sample_size_0, n_dim_0, n_info, num_rep, step_size, rnd_seed, repro)

compute the simulation with sample size 100 and number of variables 150

In [6]:
df1

,algo,Number of selected variables (mean),Number of selected variables (median)
0,bsolar-3S,5.47,5.0
1,bsolar-3H,5.47,5.0
2,bsolar-10S,5.03,5.0
3,bsolar-10H,5.03,5.0
4,bsolar-5S,5.15,5.0
5,bsolar-5H,5.15,5.0
6,bolasso-S,5.39,5.0
7,bolasso-H,5.00,5.0

In [7]:
df2

,algo,Pr(select X0),Pr(select X1),Pr(select X2),Pr(select X3),Pr(select X4)
0,bsolar-3S,1.00,1.0,1.0,1.0,1.0
1,bsolar-3H,1.00,1.0,1.0,1.0,1.0
2,bsolar-10S,0.99,1.0,1.0,1.0,1.0
3,bsolar-10H,0.99,1.0,1.0,1.0,1.0
4,bsolar-5S,1.00,1.0,1.0,1.0,1.0
5,bsolar-5H,1.00,1.0,1.0,1.0,1.0
6,bolasso-S,1.00,1.0,1.0,1.0,1.0
7,bolasso-H,1.00,1.0,1.0,1.0,1.0

## #4(b): $p/n=200/150$

In [8]:
df1, df2 = func_simul(sample_size_1, n_dim_1, n_info, num_rep, step_size, rnd_seed, repro)

compute the simulation with sample size 150 and number of variables 200

In [9]:
df1

,algo,Number of selected variables (mean),Number of selected variables (median)
0,bsolar-3S,5.17,5.0
1,bsolar-3H,5.17,5.0
2,bsolar-10S,5.00,5.0
3,bsolar-10H,5.00,5.0
4,bsolar-5S,5.04,5.0
5,bsolar-5H,5.04,5.0
6,bolasso-S,5.72,5.0
7,bolasso-H,5.01,5.0

In [10]:
df2

,algo,Pr(select X0),Pr(select X1),Pr(select X2),Pr(select X3),Pr(select X4)
0,bsolar-3S,1.0,1.0,1.0,1.0,1.0
1,bsolar-3H,1.0,1.0,1.0,1.0,1.0
2,bsolar-10S,1.0,1.0,1.0,1.0,1.0
3,bsolar-10H,1.0,1.0,1.0,1.0,1.0
4,bsolar-5S,1.0,1.0,1.0,1.0,1.0
5,bsolar-5H,1.0,1.0,1.0,1.0,1.0
6,bolasso-S,1.0,1.0,1.0,1.0,1.0
7,bolasso-H,1.0,1.0,1.0,1.0,1.0

## #4(c): $p/n=250/200$

In [11]:
df1, df2 = func_simul(sample_size_2, n_dim_2, n_info, num_rep, step_size, rnd_seed, repro)

compute the simulation with sample size 200 and number of variables 250

In [12]:
df1

,algo,Number of selected variables (mean),Number of selected variables (median)
0,bsolar-3S,5.07,5.0
1,bsolar-3H,5.07,5.0
2,bsolar-10S,5.00,5.0
3,bsolar-10H,5.00,5.0
4,bsolar-5S,5.04,5.0
5,bsolar-5H,5.04,5.0
6,bolasso-S,6.06,6.0
7,bolasso-H,5.00,5.0

In [13]:
df2

,algo,Pr(select X0),Pr(select X1),Pr(select X2),Pr(select X3),Pr(select X4)
0,bsolar-3S,1.0,1.0,1.0,1.0,1.0
1,bsolar-3H,1.0,1.0,1.0,1.0,1.0
2,bsolar-10S,1.0,1.0,1.0,1.0,1.0
3,bsolar-10H,1.0,1.0,1.0,1.0,1.0
4,bsolar-5S,1.0,1.0,1.0,1.0,1.0
5,bsolar-5H,1.0,1.0,1.0,1.0,1.0
6,bolasso-S,1.0,1.0,1.0,1.0,1.0
7,bolasso-H,1.0,1.0,1.0,1.0,1.0

In [1]:
!rm -rf Simul_3b.html
!jupyter nbconvert --to html Simul_3b.ipynb

[NbConvertApp] Converting notebook Simul_3b.ipynb to html
[NbConvertApp] Writing 632843 bytes to Simul_3b.html